Created temporary directory: /tmp/pip-ephem-wheel-cache-9akt5X
Created temporary directory: /tmp/pip-req-tracker-2QIyeo
Created requirements tracker '/tmp/pip-req-tracker-2QIyeo'
Created temporary directory: /tmp/pip-install-rYnX7e
Collecting starterkit-ci
  1 location(s) to search for versions of starterkit-ci:
  * https://pypi.org/simple/starterkit-ci/
  Getting page https://pypi.org/simple/starterkit-ci/
  Looking up "https://pypi.org/simple/starterkit-ci/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/starterkit-ci/ HTTP/1.1" 200 1310
  Updating cache with response from "https://pypi.org/simple/starterkit-ci/"
  Caching due to etag
  Analyzing links from page https://pypi.org/simple/starterkit-ci/
    The package https://files.pythonhosted.org/packages/bb/33/e086a0a997331e1674b3ed7a3b9f196a24d78ac1008bd7c51ed16e752f7c/starterkit_ci-0.0.1.tar.gz#sha256=f522b7f2ffbc07427a82e1f77e4b010424872bd1dfd4ed41662d3bb387dd965a (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/47/c7/915dde9474800339713c0be999ec1ebc0b79ce3f5601ea64c98a0ecff3e1/starterkit_ci-0.0.2.tar.gz#sha256=269172935abe85debc95731948640ea1bc50f1df83d2fa692658fe6a85241474 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/2e/05/1b0cdda72b449916c068259792877cd43d7843aec0991b9f5911c8d948a5/starterkit_ci-0.0.3.tar.gz#sha256=f0035e1c7dc63c8bc08e6874350e37121006493e99baaa75e8dbdea573f67068 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/8a/1e/fd1e68aa4c79deace65f73ca1b4231df1bce65b20bbb49d4b1a9dcd59552/starterkit_ci-0.0.4.tar.gz#sha256=fe2d58bc6f2ef822d4edcc68a0dee52f9851c6719cd4bc5a12b87b28ad95f743 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/d9/f7/266bea4fd6d43fc8060287ae3e3f39ea8cb1fb355d69e0f3e9b2937abe6c/starterkit_ci-0.0.5.tar.gz#sha256=d8f2ba5f1fcad5282a90bcde19e0f0eebc83d500e3e9916255629e3d9851b021 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/9c/3f/6affb698a880eb65b41fdef561c87104081d196f8e906c60cc9525bd01ca/starterkit_ci-0.0.6.tar.gz#sha256=e6a842cb9fda0708e45ac7310bd95c6e08243fa977949aa49df4a2ff2885b428 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/49/e9/d564bb20b1c59406254f4f2627967477712c6baacd5cfca817327087febf/starterkit_ci-0.0.7.tar.gz#sha256=b61fea7e12d5343f8c26e5606d55e5ab8a68c7735ae4eb96a5e0e8ec810b8c92 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/96/0e/ff790e07b1b5f9dcf3c99bf4a5bbc224d818358d5f5c24f86f66dbd7caaf/starterkit_ci-0.0.8.tar.gz#sha256=2e4e4597c35d6f4066861b8de8cd37f36405d286ba6f82b94c5263a3666a807e (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/cf/25/64457b617069f64ab1f85afb4add85bfb8f3d7eed930d41baac511ae95f1/starterkit_ci-0.0.9.tar.gz#sha256=78a39da770bc5d4b3527c7176cd737c893e455284be47d928df261c9e0494fd6 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/e3/bc/03f6eb2d53fe85210827eced60566ed008c5ee29560bc3b1e3b9823124c8/starterkit_ci-0.0.10.tar.gz#sha256=1ad733be2def29ed542483f4d2b33ce6610cf8d53cb033d69ecafb134ed45410 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/1c/9f/bea5a6c48b4ac2c357d93a9013bd0f84c8c9eb78bfad013015e0f9ffb4cc/starterkit_ci-0.0.11.tar.gz#sha256=c47df1287d84fcb34e667fd6054bf05a8c5e3ac02fa5952c3417f7d730648d28 (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
    The package https://files.pythonhosted.org/packages/4b/e1/9eb6d8f83dc7b97531f8f24fff95696e66633192c5cba844087dc4b5ac38/starterkit_ci-0.0.12.tar.gz#sha256=76e06ff827956ef780949af70fae0d20772ca48e576a777c1f14a3809591f3db (from https://pypi.org/simple/starterkit-ci/) (requires-python:>=3.6) is incompatible with the python version in use. Acceptable python versions are: >=3.6
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-2QIyeo'
Exception information:
Traceback (most recent call last):
  File "/home/vali/.local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/vali/.local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/home/vali/.local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/vali/.local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/vali/.local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/vali/.local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 282, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/home/vali/.local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 198, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/vali/.local/lib/python2.7/site-packages/pip/_internal/index.py", line 792, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for starterkit-ci
